### ISSUE TITLE
GitBook Community in Google+

### ISSUE THREAD

**Issue by aleen42** [denysdovhan/gitbook-plugin-rss#4]
Hi denysdovhan,

I am Aleen (https://github.com/aleen42) , and the founder of GitBook Community in Google+: https://plus.google.com/communities/110696788983472771007, which aims to sharing books or plugins of GitBook, talking anything about it as well. Here I am sincerely inviting you to join us.  :punch:

**Comment by denysdovhan** [comment]
I am not an active user of G+, but yep, sure I accept your invite :)

**Comment by aleen42** [comment]
@denysdovhan Thx.
